namespace TravelPrototype.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class Inital : DbMigration
    {
        public override void Up()
        {
            //CreateTable(
            //    "dbo.ItineraryModels",
            //    c => new
            //        {
            //            ID = c.Int(nullable: false, identity: true),
            //            member_id = c.Int(nullable: false),
            //            itinerary_id = c.Int(nullable: false),
            //            status = c.String(),
            //            first_name = c.String(),
            //            last_name = c.String(),
            //            destination = c.String(),
            //            state = c.String(),
            //            postal_code = c.String(),
            //            country = c.String(),
            //            begin_datetime = c.DateTime(nullable: false),
            //            begin_time_zone = c.String(),
            //            begin_time_zone_id = c.String(),
            //            end_datetime = c.DateTime(nullable: false),
            //            end_time_zone = c.String(),
            //            end_time_zone_id = c.String(),
            //            lat = c.String(),
            //            lon = c.String(),
            //            privacy = c.String(),
            //            personal = c.Int(nullable: false),
            //            business = c.Int(nullable: false),
            //            verified = c.String(),
            //            distance = c.Single(nullable: false),
            //            duration = c.String(),
            //            headline = c.String(),
            //            harvested = c.String(),
            //            created = c.DateTime(nullable: false),
            //            updated = c.DateTime(nullable: false),
            //        })
            //    .PrimaryKey(t => t.ID);
            
            //CreateTable(
            //    "dbo.SegmentModels",
            //    c => new
            //        {
            //            id = c.Int(nullable: false, identity: true),
            //            member_id = c.Int(nullable: false),
            //            type = c.String(),
            //            status = c.String(),
            //            hotel_name = c.String(),
            //            normalized_hotel_chain = c.String(),
            //            phone = c.String(),
            //            first_name = c.String(),
            //            last_name = c.String(),
            //            address1 = c.String(),
            //            address2 = c.String(),
            //            city_name = c.String(),
            //            admin_code = c.String(),
            //            country = c.String(),
            //            zip = c.String(),
            //            lat = c.String(),
            //            lon = c.String(),
            //            checkin_date = c.DateTime(nullable: false),
            //            checkin_time_zone = c.String(),
            //            checkout_date = c.DateTime(nullable: false),
            //            checkout_time_zone = c.String(),
            //            time_zone_id = c.String(),
            //            price = c.Single(nullable: false),
            //            currency = c.String(),
            //            number_of_rooms = c.Int(nullable: false),
            //            confirmation_no = c.String(),
            //            support_phone = c.String(),
            //            booking_agent = c.String(),
            //            room_type = c.String(),
            //            room_description = c.String(),
            //            rate_description = c.String(),
            //            cancellation_policy = c.String(),
            //            source = c.String(),
            //            harvested = c.String(),
            //            hotel_notes = c.String(),
            //            created = c.DateTime(nullable: false),
            //            updated = c.DateTime(nullable: false),
            //            metadata = c.String(),
            //            airline = c.String(),
            //            iata_code = c.String(),
            //            normalized_airline = c.String(),
            //            flight_num = c.String(),
            //            seat_assignment = c.String(),
            //            origin = c.String(),
            //            origin_city_name = c.String(),
            //            origin_admin_code = c.String(),
            //            origin_country = c.String(),
            //            origin_lat = c.String(),
            //            origin_lon = c.String(),
            //            departure_datetime = c.DateTime(nullable: false),
            //            departure_time_zone = c.String(),
            //            departure_time_zone_id = c.String(),
            //            arrival_datetime = c.DateTime(nullable: false),
            //            arrival_time_zone = c.String(),
            //            arrival_time_zone_id = c.String(),
            //            pax_number = c.String(),
            //            ticket_number = c.String(),
            //            class_of_service = c.String(),
            //            meal = c.String(),
            //            stops = c.String(),
            //            duration = c.String(),
            //            equipment_code = c.String(),
            //            equipment_type = c.String(),
            //            departure_terminal = c.String(),
            //            departure_gate = c.String(),
            //            arrival_terminal = c.String(),
            //            arrival_gate = c.String(),
            //            air_notes = c.String(),
            //            car_company = c.String(),
            //            normalized_car_company = c.String(),
            //            pickup_address1 = c.String(),
            //            pickup_address2 = c.String(),
            //            pickup_city_name = c.String(),
            //            pickup_city_code = c.String(),
            //            pickup_admin_code = c.String(),
            //            pickup_country = c.String(),
            //            pickup_zip = c.String(),
            //            pickup_lat = c.String(),
            //            pickup_lon = c.String(),
            //            pickup_datetime = c.DateTime(nullable: false),
            //            pickup_time_zone = c.String(),
            //            pickup_time_zone_id = c.String(),
            //            dropoff_address1 = c.String(),
            //            dropoff_address2 = c.String(),
            //            dropoff_city_name = c.String(),
            //            dropoff_city_code = c.String(),
            //            dropoff_admin_code = c.String(),
            //            dropoff_country = c.String(),
            //            dropoff_zip = c.String(),
            //            dropoff_lat = c.String(),
            //            dropoff_lon = c.String(),
            //            dropoff_datetime = c.DateTime(nullable: false),
            //            dropoff_time_zone = c.String(),
            //            dropoff_time_zone_id = c.String(),
            //            reservation_id = c.String(),
            //            car_type = c.String(),
            //            car_description = c.String(),
            //            hours_of_operation = c.String(),
            //            car_notes = c.String(),
            //            activity_type = c.String(),
            //            activity_name = c.String(),
            //            end_address1 = c.String(),
            //            end_address2 = c.String(),
            //            end_city_name = c.String(),
            //            end_admin_code = c.String(),
            //            end_country = c.String(),
            //            end_zip = c.String(),
            //            end_lat = c.String(),
            //            end_lon = c.String(),
            //            start_datetime = c.DateTime(nullable: false),
            //            start_time_zone = c.String(),
            //            start_time_zone_id = c.String(),
            //            end_datetime = c.DateTime(nullable: false),
            //            end_time_zone = c.String(),
            //            end_time_zone_id = c.String(),
            //            activity_notes = c.String(),
            //            ItineraryModel_ID = c.Int(),
            //        })
            //    .PrimaryKey(t => t.id)
            //    .ForeignKey("dbo.ItineraryModels", t => t.ItineraryModel_ID)
            //    .Index(t => t.ItineraryModel_ID);
            
        }
        
        public override void Down()
        {
            //DropForeignKey("dbo.SegmentModels", "ItineraryModel_ID", "dbo.ItineraryModels");
            //DropIndex("dbo.SegmentModels", new[] { "ItineraryModel_ID" });
            //DropTable("dbo.SegmentModels");
            //DropTable("dbo.ItineraryModels");
        }
    }
}
